### ISSUE TITLE
Cannot change timezone when run as a container

### ISSUE THREAD

**Issue by mapshen** [allangood/holiday_exporter#5]
When we run holiday-exporter as a container and the time defaults to UTC, so that `is_daylight_saving_time` is always evaluated to 0 even we're using DST.

```
/ $ python -c  "import time;print(time.localtime())"
time.struct_time(tm_year=2020, tm_mon=3, tm_mday=27, tm_hour=15, tm_min=14, tm_sec=22, tm_wday=4, tm_yday=87, tm_isdst=0)
```

Simply starting the container with `TZ` set won't work either 
```
docker run -e TZ=America/New_York holiday_exporter
```

as an alpine based image requires `tzdata`.

Could we have `RUN apk add --no-cache tzdata` added to `Dockerfile` please?

Thanks,
Map

**Comment by allangood** [comment]
Hi @mapshen ,

Actually is not necessary to add the tzdata package inside the container. If you share your local tzdata file it works without any problem.

Just add this to your docker run command:
```
-v /etc/localtime:/etc/localtime:ro
```
But I should add this to the README file.

**Comment by mapshen** [comment]
@allangood , thanks for your reply! 

Would you oppose the idea of having the `tzdata` package, which is < 0.5 MB, built into the image? IMHO, an image should be always self-contained if possible. If the host doesn't have `/etc/localtime`, mounting it at runtime won't work.

**Comment by allangood** [comment]
Hi @mapshen , you are right, although the tzdata package is 3.38MB, but this will not make any difference IMO.

The tzdata package was added to the latest version.

Thank you for your feedback!
